### ISSUE TITLE
spawnpoint

### ISSUE THREAD

**Issue by pokecatchy** [pokecatchy/Pokemap#2]
hi,  can anyone explain why spawnpoint needs to be lowercase even though the refered project writes it uppercase in the middle ? 
maybe there needs the building to be changed ... but i have no idea about it

**Comment by pokecatchy** [comment]
maybe it's the grade cache in the home directory

**Comment by pokecatchy** [comment]
that's it 

delete ~/.gradle

**Comment by kyr0** [comment]
Well, actually this was exactly my problem too :) "Invalidate caches and restart" seems to clean up .gradle too (?). I also removed  ~/.gradle explicitly now.

At the moment on my side, following situation: 
When it is uppercase, it works for me. When it is lowercase it doesn't. (Newest commit seems to be lowercase, so after pull it broke again) -- I changed it locally, and it works fine ;)

**Comment by pokecatchy** [comment]
yes .. .it works for me now uppercase too

**Comment by pokecatchy** [comment]
however introspection into pokegoapi is lost

**Comment by kyr0** [comment]
Ah, try the invalidate caches and restart, for me the introspection works again :)

**Comment by kyr0** [comment]
(But be careful, you may loose the local file history!!)

**Comment by pokecatchy** [comment]
# solution:  ToolBarButton "Sync Project with Gradle Files"
