### ISSUE TITLE
Long tap to getCatchablePokemon() at specific lat/long

### ISSUE THREAD

**Issue by kyr0** [pokecatchy/Pokemap#3]
I'm thinking about having a way to "scan" around you. A long-tap could resolve the lat/long and we could just call fetchCatchablePokemon() for that specific location. What do you think? Should I implement and push it?

**Comment by pokecatchy** [comment]
why not

2016-07-23 22:35 GMT+02:00 Aron Homberg <notifications@github.com>:

**Comment by pokecatchy** [comment]
i guess it will require to have the "walking" set to zero that instant and possibly the current loop might be too quick to reset the position .. so maybe combining that with the FloatingActionButton to renable the localisation

**Comment by kyr0** [comment]
yep sounds good

**Comment by pokecatchy** [comment]
well, better include the code in the main fork at https://github.com/omkarmoghe/Pokemap 
i will remove this fork alltogether
